spring:
  application:
    name: ai-code-chat

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: deepseek-r1
        api-key: sk-b80db79d4ac24cb8b4c6c53ee60fb387
      embedding-model:
        model-name: text-embedding-v2
        api-key: sk-b80db79d4ac24cb8b4c6c53ee60fb387